"""
Cohomology projection module.

Projects defects onto the regular sector H²_reg and computes cohomological norms.
For exponential transfers, a 2-cochain g is exponentially regular if:
    g(a,b) = μα^{a+b} + να^{ab}

In the regular sector, H²_{α,reg} ≅ ℝ, generated by [δ_α].
"""

from typing import Tuple, Optional, Union, Dict, Any
from mpmath import mp, mpf, fabs, sqrt as mp_sqrt, log as mp_log
import numpy as np
from scipy.optimize import least_squares

from arithmetics.core.transfer import ArithmeticTransfer, ExponentialTransfer
from arithmetics.core.defect import compute_defect, DefectMatrix


def project_to_regular_sector(
    phi: ArithmeticTransfer,
    defect_matrix: Optional[DefectMatrix] = None,
    precision: int = 50
) -> Tuple[mpf, mpf]:
    """
    Project the defect onto the exponentially regular sector.

    For exponential transfer φ_α, find μ, ν such that
    δ(a,b) ≈ μα^{a+b} + να^{ab}

    The projection minimizes ||δ - (μα^{a+b} + να^{ab})||² over test pairs.

    Args:
        phi: The arithmetic transfer (typically ExponentialTransfer)
        defect_matrix: Pre-computed defect matrix (computed if None)
        precision: Decimal places for computation

    Returns:
        Tuple (μ, ν) of projection coefficients
    """
    mp.dps = precision
    phi.precision = precision

    if defect_matrix is None:
        defect_matrix = DefectMatrix(phi, precision=precision)

    # For exponential transfer, we fit δ(a,b) = μα^{a+b} + να^{ab}
    if isinstance(phi, ExponentialTransfer):
        alpha = float(phi.alpha)
    else:
        # For non-exponential transfers, we still try to fit but results may not be meaningful
        alpha = 2.0  # Default base

    # Build system of equations for least squares
    a_vals = defect_matrix.a_values
    b_vals = defect_matrix.b_values

    # Construct design matrix A and target vector y
    A_rows = []
    y_vals = []

    for i, a in enumerate(a_vals):
        for j, b in enumerate(b_vals):
            # Columns: [α^{a+b}, α^{ab}]
            col1 = alpha ** (a + b)
            col2 = alpha ** (a * b)
            A_rows.append([col1, col2])
            y_vals.append(float(defect_matrix.matrix[i][j]))

    A = np.array(A_rows)
    y = np.array(y_vals)

    # Solve least squares: A @ [μ, ν]ᵀ = y
    result, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)

    mu, nu = result[0], result[1]

    return mpf(mu), mpf(nu)


def compute_regular_norm(
    phi: ArithmeticTransfer,
    defect_matrix: Optional[DefectMatrix] = None,
    precision: int = 50
) -> mpf:
    """
    Compute the norm ||[δ_φ]|| in the regular sector H²_reg.

    For exponential transfers, this is essentially |μ + ν| since
    a cocycle in Z²_reg has μ + ν = 0.

    The defect δ_α(a,b) = α^{a+b} - α^{ab} corresponds to μ = 1, ν = -1.

    Args:
        phi: The arithmetic transfer
        defect_matrix: Pre-computed defect matrix
        precision: Decimal places for computation

    Returns:
        The norm ||[δ_φ]|| as an mpf
    """
    mp.dps = precision

    if defect_matrix is None:
        defect_matrix = DefectMatrix(phi, precision=precision)

    mu, nu = project_to_regular_sector(phi, defect_matrix, precision)

    # The canonical defect δ_α has μ = 1, ν = -1
    # The norm in the regular sector is |μ| (since we quotient by coboundaries)
    # For general defects, we use the L² norm of the projected component
    norm = mp_sqrt(mu * mu + nu * nu)

    return norm


def classify_defect(
    phi: ArithmeticTransfer,
    precision: int = 50,
    tolerance: Optional[mpf] = None
) -> Dict[str, Any]:
    """
    Classify the defect as zero or non-zero and determine its properties.

    Args:
        phi: The arithmetic transfer
        precision: Decimal places for computation
        tolerance: Threshold for zero classification

    Returns:
        Dictionary with classification results
    """
    mp.dps = precision
    phi.precision = precision

    if tolerance is None:
        tolerance = mpf(10) ** (-(precision - 10))

    defect_matrix = DefectMatrix(phi, precision=precision)

    # Basic statistics
    is_zero = defect_matrix.is_zero_defect(tolerance)
    max_val, max_a, max_b = defect_matrix.max_defect()
    mean_val = defect_matrix.mean_defect()

    # Verify cocycle identity
    cocycle_valid, failures = defect_matrix.verify_all_cocycles(tolerance=tolerance)

    # Project to regular sector
    mu, nu = project_to_regular_sector(phi, defect_matrix, precision)
    regular_norm = compute_regular_norm(phi, defect_matrix, precision)

    # Compute residual after projection (how well does regular sector fit?)
    if isinstance(phi, ExponentialTransfer):
        alpha = float(phi.alpha)
        residual_sum = mpf(0)
        for i, a in enumerate(defect_matrix.a_values):
            for j, b in enumerate(defect_matrix.b_values):
                actual = defect_matrix.matrix[i][j]
                projected = mu * mpf(alpha ** (a + b)) + nu * mpf(alpha ** (a * b))
                residual_sum += (actual - projected) ** 2
        projection_residual = mp_sqrt(residual_sum)
    else:
        projection_residual = mpf('nan')

    # Cohomology class
    if is_zero:
        cohomology_class = "trivial"
        h2_dimension = 0
    else:
        cohomology_class = "non-trivial"
        h2_dimension = 1  # H²_{α,reg} ≅ ℝ for exponential

    return {
        'transfer_name': phi.name,
        'is_zero_defect': is_zero,
        'cohomology_class': cohomology_class,
        'h2_dimension': h2_dimension,
        'max_defect': float(max_val),
        'max_at': (max_a, max_b),
        'mean_defect': float(mean_val),
        'mu': float(mu),
        'nu': float(nu),
        'regular_norm': float(regular_norm),
        'projection_residual': float(projection_residual) if projection_residual == projection_residual else None,
        'cocycle_identity_satisfied': cocycle_valid,
        'cocycle_failures': len(failures),
        'precision': precision,
    }


def compute_curvature_bracket(
    phi: ArithmeticTransfer,
    f_values: Dict[int, mpf],
    a: int,
    b: int,
    c: int,
    precision: int = 50
) -> mpf:
    """
    Compute the curvature bracket [δ, f](a,b,c) = δ(a,b)f(c) - f(a)δ(b,c).

    This arises from Theorem 3.2: (d² ∘ d¹)(f) = [δ, f].

    Args:
        phi: The arithmetic transfer
        f_values: Dictionary mapping integers to f(n) values
        a, b, c: Test values
        precision: Decimal places for computation

    Returns:
        The curvature bracket value
    """
    mp.dps = precision
    phi.precision = precision

    delta_ab = compute_defect(phi, a, b, precision)
    delta_bc = compute_defect(phi, b, c, precision)

    f_a = f_values.get(a, mpf(0))
    f_c = f_values.get(c, mpf(0))

    return delta_ab * f_c - f_a * delta_bc


def verify_nontriviality(
    phi: ExponentialTransfer,
    precision: int = 50
) -> Tuple[bool, Dict[str, Any]]:
    """
    Verify that δ ∉ Im(d¹), i.e., the defect is not a coboundary.

    This implements the proof of Theorem 4.1: there is no f such that d¹f = δ.

    For exponential transfer with δ(a,b) = α^{a+b} - α^{ab}:
    - If d¹f = δ, then setting a=1 gives f(b) = βα^b for some β
    - Substituting back gives 2β = 1 and β = 1, a contradiction

    Args:
        phi: An ExponentialTransfer
        precision: Decimal places for computation

    Returns:
        Tuple (is_nontrivial, details)
    """
    mp.dps = precision
    phi.precision = precision

    alpha = phi.alpha

    # From the proof: if d¹f = δ with a=1, we get f(b) = βα^b
    # where β = 1 - f(1)/(α-1)
    #
    # Then d¹f(a,b) = α^a·βα^b - βα^{ab} + βα^a·α^b = 2βα^{a+b} - βα^{ab}
    #
    # For this to equal δ(a,b) = α^{a+b} - α^{ab}, we need:
    # 2β = 1 and β = 1
    # This is impossible, so δ is non-trivial

    # Verify numerically by checking that no β satisfies both conditions
    beta_from_sum = mpf('0.5')  # From 2β = 1
    beta_from_product = mpf('1')  # From β = 1

    contradiction = fabs(beta_from_sum - beta_from_product) > tolerance_for_precision(precision)

    # Also verify by trying to fit f(n) = βα^n and checking residual
    test_pairs = [(2, 3), (3, 4), (2, 5), (3, 5)]
    residuals = []

    for beta in [mpf('0.3'), mpf('0.5'), mpf('0.7'), mpf('1.0')]:
        # d¹f(a,b) = α^a·f(b) - f(ab) + f(a)·α^b where f(n) = βα^n
        total_residual = mpf(0)
        for a, b in test_pairs:
            f_a = beta * (alpha ** a)
            f_b = beta * (alpha ** b)
            f_ab = beta * (alpha ** (a * b))
            phi_a = alpha ** a
            phi_b = alpha ** b

            d1f = phi_a * f_b - f_ab + f_a * phi_b
            delta = compute_defect(phi, a, b, precision)
            total_residual += (d1f - delta) ** 2

        residuals.append((float(beta), float(mp_sqrt(total_residual))))

    # Find minimum residual
    min_residual = min(residuals, key=lambda x: x[1])

    details = {
        'alpha': float(alpha),
        'beta_from_coefficient_of_exp': float(beta_from_sum),
        'beta_from_coefficient_of_prod': float(beta_from_product),
        'contradiction_verified': contradiction,
        'best_beta_fit': min_residual[0],
        'best_residual': min_residual[1],
        'all_residuals': residuals,
    }

    return contradiction, details


def tolerance_for_precision(precision: int) -> mpf:
    """Return appropriate tolerance for given precision."""
    return mpf(10) ** (-(precision - 5))


def compute_fibered_incompatibility(
    alpha: float,
    beta: float,
    test_triple: Tuple[int, int, int] = (1, 2, 3),
    precision: int = 50
) -> mpf:
    """
    Verify that δ_β does not satisfy the α-twisted cocycle condition.

    This implements Theorem 6.1: if α ≠ β, then D^α(δ_β) ≠ 0.

    D^α(δ)(a,b,c) = α^a δ(b,c) + δ(a,bc) - δ(a,b)α^c - δ(ab,c)

    Args:
        alpha: Base for the twisted cocycle operator
        beta: Base for the defect being tested
        test_triple: Values (a, b, c) for testing
        precision: Decimal places for computation

    Returns:
        The residual D^α(δ_β)(a,b,c), which should be non-zero if α ≠ β
    """
    mp.dps = precision

    a, b, c = test_triple
    alpha = mpf(alpha)
    beta = mpf(beta)

    # δ_β(x,y) = β^{x+y} - β^{xy}
    def delta_beta(x, y):
        return beta ** (x + y) - beta ** (x * y)

    # D^α(δ_β)(a,b,c) = α^a δ_β(b,c) + δ_β(a,bc) - δ_β(a,b)α^c - δ_β(ab,c)
    term1 = (alpha ** a) * delta_beta(b, c)
    term2 = delta_beta(a, b * c)
    term3 = delta_beta(a, b) * (alpha ** c)
    term4 = delta_beta(a * b, c)

    D_alpha_delta_beta = term1 + term2 - term3 - term4

    return D_alpha_delta_beta


class CohomologyAnalyzer:
    """
    Comprehensive analyzer for the cohomological structure of a transfer.
    """

    def __init__(self, phi: ArithmeticTransfer, precision: int = 50):
        """
        Initialize the analyzer.

        Args:
            phi: The arithmetic transfer to analyze
            precision: Decimal places for computations
        """
        self.phi = phi
        self.precision = precision
        self.defect_matrix = None
        self._classification = None

    def analyze(self) -> Dict[str, Any]:
        """
        Perform complete cohomological analysis.

        Returns:
            Dictionary with all analysis results
        """
        # Compute defect matrix
        self.defect_matrix = DefectMatrix(self.phi, precision=self.precision)

        # Classify defect
        self._classification = classify_defect(self.phi, self.precision)

        # Additional analysis for exponential transfers
        if isinstance(self.phi, ExponentialTransfer):
            is_nontrivial, nontriviality_details = verify_nontriviality(
                self.phi, self.precision
            )
            self._classification['nontriviality_verified'] = is_nontrivial
            self._classification['nontriviality_details'] = nontriviality_details

            # Test fibered incompatibility with nearby bases
            alpha = float(self.phi.alpha)
            incompatibilities = {}
            for beta in [alpha * 0.5, alpha * 1.5, alpha + 1, alpha - 0.5]:
                if beta > 0 and beta != alpha:
                    incompat = compute_fibered_incompatibility(alpha, beta, precision=self.precision)
                    incompatibilities[f'beta={beta:.3f}'] = float(incompat)
            self._classification['fibered_incompatibilities'] = incompatibilities

        return self._classification

    def get_h2_generator(self) -> Optional[Tuple[mpf, mpf]]:
        """
        Get the generator of H²_{α,reg}.

        For exponential transfers, this is [δ_α] with μ=1, ν=-1.

        Returns:
            Tuple (μ, ν) for the canonical generator, or None
        """
        if self._classification is None:
            self.analyze()

        if self._classification['is_zero_defect']:
            return None

        return (mpf(1), mpf(-1))  # Canonical generator

    def summary(self) -> str:
        """Generate a human-readable summary."""
        if self._classification is None:
            self.analyze()

        c = self._classification
        lines = [
            f"Cohomology Analysis for {c['transfer_name']}",
            "=" * 50,
            f"Defect class: {c['cohomology_class']}",
            f"H² dimension: {c['h2_dimension']}",
            f"Max defect: {c['max_defect']:.6e} at {c['max_at']}",
            f"Mean defect: {c['mean_defect']:.6e}",
            f"Regular sector projection: μ={c['mu']:.6f}, ν={c['nu']:.6f}",
            f"Regular norm ||[δ]||: {c['regular_norm']:.6f}",
            f"Cocycle identity: {'satisfied' if c['cocycle_identity_satisfied'] else 'FAILED'}",
        ]

        if 'nontriviality_verified' in c:
            lines.append(f"Non-triviality: {'verified' if c['nontriviality_verified'] else 'not verified'}")

        return "\n".join(lines)
